// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Synapse.Data;

namespace Synapse.Migrations
{
    [DbContext(typeof(SynapseContext))]
    [Migration("20210415172003_addStatus")]
    partial class addStatus
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {

        }
    }
}
